name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 UTC
    - cron: '0 12 * * *'

jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@maste
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
